CREATE VIEW `jd_industry_compete_brand_info`
            (
             `username`,
             `skuCid3`,
             `brandId`,
             `caliber`,
             `order_status`,
             `gift_flag`,
             `effect`,
             `is_daily`,
             `start_date`,
             `end_date`,
             `period`,
             `pin`,
             `business`,
             `campaign_type`,
             `campaign_id`,
             `campaign_name`,
             `group_id`,
             `group_name`,
             `kw_id`,
             `keyword`,
             `target_type`,
             `sku_brand_id`,
             `sku_brand_name`,
             `impressions`,
             `clicks`,
             `all_cost`,
             `dir_ord_cnt`,
             `dir_ord_sum`,
             `ind_ord_cnt`,
             `ind_ord_sum`,
             `tot_ord_cnt`,
             `tot_ord_sum`,
             `dir_cart_cnt`,
             `ind_cart_cnt`,
             `tot_cart_cnt`,
             `new_customer`,
             `ad_id`,
             `ad_name`,
             `search_term`,
             `download_id`,
             `record_load_time`,
             `batch`,
             `kc_dt`
                )
AS
SELECT `ods`.`a`.`id`,
       `ods`.`a`.`username`,
       `ods`.`a`.`date_str`,
       `ods`.`a`.`trans_days`,
       `ods`.`a`.`caliber`,
       `ods`.`a`.`order_status`,
       `ods`.`a`.`gift_flag`,
       `ods`.`a`.`effect`,
       `ods`.`a`.`is_daily`,
       `ods`.`a`.`start_date`,
       `ods`.`a`.`end_date`,
       `ods`.`a`.`period`,
       `ods`.`a`.`pin`,
       `ods`.`a`.`business`,
       `ods`.`a`.`campaign_type`,
       `ods`.`a`.`campaign_id`,
       `ods`.`a`.`campaign_name`,
       `ods`.`a`.`group_id`,
       `ods`.`a`.`group_name`,
       `ods`.`a`.`kw_id`,
       `ods`.`a`.`keyword`,
       `ods`.`a`.`target_type`,
       `ods`.`a`.`sku_brand_id`,
       `ods`.`a`.`sku_brand_name`,
       `ods`.`a`.`impressions`,
       `ods`.`a`.`clicks`,
       `ods`.`a`.`all_cost`,
       `ods`.`a`.`dir_ord_cnt`,
       `ods`.`a`.`dir_ord_sum`,
       `ods`.`a`.`ind_ord_cnt`,
       `ods`.`a`.`ind_ord_sum`,
       `ods`.`a`.`tot_ord_cnt`,
       `ods`.`a`.`tot_ord_sum`,
       `ods`.`a`.`dir_cart_cnt`,
       `ods`.`a`.`ind_cart_cnt`,
       `ods`.`a`.`tot_cart_cnt`,
       `ods`.`a`.`new_customer`,
       `ods`.`a`.`ad_id`,
       `ods`.`a`.`ad_name`,
       `ods`.`a`.`search_term`,
       `ods`.`a`.`download_id`,
       `ods`.`a`.`record_load_time`,
       `ods`.`a`.`batch`,
       `ods`.`a`.`kc_dt`
FROM `ods`.`jd_custom_report_keyword` AS `a`
         INNER JOIN `jd_digital_marketing`.`jd_custom_report_batch` AS `b` ON ((((((
                                                                                       `ods`.`a`.`username` = `jd_digital_marketing`.`b`.`username`
                                                                                       )
    AND (`ods`.`a`.`date_str` = `jd_digital_marketing`.`b`.`date_str`))
    AND (`ods`.`a`.`trans_days` = `jd_digital_marketing`.`b`.`trans_days`))
    AND (`ods`.`a`.`caliber` = `jd_digital_marketing`.`b`.`caliber`))
    AND (`ods`.`a`.`order_status` = `jd_digital_marketing`.`b`.`order_status`))
    AND (`ods`.`a`.`batch` = `jd_digital_marketing`.`b`.`batch`))
    AND (`jd_digital_marketing`.`b`.`template_key` = 'jd_custom_report_keyword');