#所有环境公用的配置属性
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/algorithm
    hikari:
      username: root
      password: liangbing39024&
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
server:
  port: 800

#jedis的配置
jedis.host: 127.0.0.1
jedis.port: 6379

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

---
#profile=x的专用属性
#开发环境
spring:
  profiles: dev

---
#profile=y的专用属性
#生产环境

spring:
  profiles: prod
server:
  tomcat:
    max-connections: 1000
    threads:
      max: 300



