spring:
  datasource:
    url: jdbc:mysql://localhost:3306/algorithm
    hikari:
      username: root
      password: liangbing39024&
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
