#所有环境公用的配置属性
spring:
  datasource:
    url: jdbc:mysql://offline-tech.ikunchi.com:30037/jd_digital_marketing?useAffectedRows=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: eGaTB0mSfkL2AIRl
      driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8088
  servlet:
    session:
      timeout: 60s

#jedis的配置
jedis.host: 127.0.0.1
jedis.port: 6379

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

---
#profile=x的专用属性
#开发环境
spring:
  profiles: dev

---
#profile=y的专用属性
#生产环境

spring:
  profiles: prod
server:
  tomcat:
    max-connections: 1000
    threads:
      max: 300
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


