UPDATE jd_shop_authorize_info SET tf_open=false WHERE id=26;
UPDATE jd_shop_authorize_info SET tf_open=false WHERE id=28;
UPDATE jd_shop_authorize_info SET tf_open=false WHERE id=29;
UPDATE jd_shop_authorize_info SET tf_open=false WHERE id=30;
UPDATE jd_shop_authorize_info SET tf_open=false WHERE id=32;
UPDATE jd_shop_authorize_info SET tf_open=false WHERE id=35;
UPDATE jd_shop_authorize_info SET tf_open=false WHERE id=34;
UPDATE jd_shop_authorize_info SET tf_open=false WHERE id=36;
UPDATE jd_shop_authorize_info SET tf_open=false WHERE id=40;
UPDATE jd_shop_authorize_info SET tf_open=false WHERE id=39;
UPDATE jd_shop_authorize_info SET tf_open=false WHERE id=38;
UPDATE jd_shop_authorize_info SET access_token='88f27f406ee144eb8a07a935a39ffbbdmnda', tf_open=true, authorize_expire_time='2025-08-30 17:21:50.608' WHERE id=5;
UPDATE jd_shop_authorize_info SET access_token='355a950b18b041128cfb32abd622feeeytk1', tf_open=true, authorize_expire_time='2025-08-30 17:21:55.075' WHERE id=126;