CREATE MATERIALIZED VIEW `dwd_jd_jzt_crowd_report`
DISTRIBUTED BY HASH(`record_load_time`)
REFRESH ASYNC START("2023-07-27 18:12:00") EVERY(INTERVAL 30 MINUTE)
PROPERTIES (
"replication_num" = "2",
"replicated_storage" = "true",
"storage_medium" = "HDD"
)
AS SELECT `conditions`.`record_load_time`, `conditions`.`username`, ifnull(`conditions`.`period`, ' ') AS `period`, ifnull(`conditions`.`trans_days`, -1) AS `trans_days`, ifnull(`conditions`.`caliber`, 0) AS `caliber`, `conditions`.`gift_flag`, if(`conditions`.`order_status` IS NULL, '0', '1') AS `order_status`, `crowd_report`.`effect`, ifnull(`crowd_report`.`is_daily`, -1) AS `is_daily`, ifnull(`conditions`.`date_str`, '20000101') AS `date_str`, `crowd_report`.`pin`, `crowd_report`.`business`, `crowd_report`.`campaign_type`, `crowd_report`.`campaign_id`, `crowd_report`.`campaign_name`, `crowd_report`.`group_id`, `crowd_report`.`group_name`, `crowd_report`.`ad_id`, `crowd_report`.`ad_name`, `crowd_report`.`sku_brand_id`, `crowd_report`.`sku_brand_name`, `crowd_report`.`sku_c3_id`, `crowd_report`.`sku_c3_name`, `crowd_report`.`crowd_id`, `crowd_report`.`crowd_name`, `crowd_report`.`impressions`, `crowd_report`.`clicks`, `crowd_report`.`all_cost`, `crowd_report`.`dir_ord_cnt`, `crowd_report`.`dir_ord_sum`, `crowd_report`.`ind_ord_cnt`, `crowd_report`.`ind_ord_sum`, `crowd_report`.`tot_ord_cnt`, `crowd_report`.`tot_ord_sum`, `crowd_report`.`dir_cart_cnt`, `crowd_report`.`ind_cart_cnt`, `crowd_report`.`tot_cart_cnt`, `crowd_report`.`new_customer`, `crowd_report`.`goods_attention`, `crowd_report`.`shop_attention`, `crowd_report`.`sku_doc_id`
FROM (SELECT max(`src_jzt_crowd_report`.`record_load_time`) AS `record_load_time`, `src_jzt_crowd_report`.`username`, `src_jzt_crowd_report`.`period`, `src_jzt_crowd_report`.`trans_days`, `src_jzt_crowd_report`.`caliber`, `src_jzt_crowd_report`.`gift_flag`, `src_jzt_crowd_report`.`order_status`, `src_jzt_crowd_report`.`date_str`
FROM `crawler_pg`.`src_jzt_crowd_report`
GROUP BY `src_jzt_crowd_report`.`username`, `src_jzt_crowd_report`.`period`, `src_jzt_crowd_report`.`trans_days`, `src_jzt_crowd_report`.`caliber`, `src_jzt_crowd_report`.`gift_flag`, `src_jzt_crowd_report`.`order_status`, `src_jzt_crowd_report`.`date_str`) conditions INNER JOIN `crawler_pg`.`src_jzt_crowd_report` AS `crowd_report` ON ((((((((`crowd_report`.`username` = `conditions`.`username`) AND (`crowd_report`.`period` = `conditions`.`period`)) AND (`crowd_report`.`trans_days` = `conditions`.`trans_days`)) AND (if(`crowd_report`.`caliber` IS NULL, `conditions`.`caliber` IS NULL, `crowd_report`.`caliber` = `conditions`.`caliber`))) AND (`crowd_report`.`gift_flag` = `conditions`.`gift_flag`)) AND (if(`crowd_report`.`order_status` IS NULL, `conditions`.`order_status` IS NULL, `crowd_report`.`order_status` = `conditions`.`order_status`))) AND (`crowd_report`.`date_str` = `conditions`.`date_str`)) AND (`crowd_report`.`record_load_time` <= `conditions`.`record_load_time`)) AND (`crowd_report`.`record_load_time` >= (adddate(`conditions`.`record_load_time`, INTERVAL -30 MINUTE)));;