package com.liang.argorithm.utils;

/**
 * @author liangbingtian
 * @date 2024/05/08 下午5:11
 */
public class WordCloudTest {

    //初始化分词器final FrequencyAnalyzer frequencyAnalyzer = new FrequencyAnalyzer();frequencyAnalyzer.setWordFrequenciesToReturn(300);frequencyAnalyzer.setMinWordLength(2);String string =“xxxxxxxx”;//开始分词List<String>segment=SegmentHelper.segment(string, SegmentResultHandlers.word());System.out.println(segment);ListwordFrequencyList=frequencyAnalyzer.load(segment);//长宽Dimension dimension = new Dimension(800,600);//此处的设置采用内置常量即可，生成词云对象        WordCloud wordCloud = new WordCloud(dimension,CollisionMode.PIXEL_PERFECT);        //设置边界及字体        wordCloud.setPadding(2);        java.awt.Font font = new java.awt.Font("STSong-Light", 2, 20);//设置词云显示的三种颜色，越靠前设置表示词频越高的词语的颜色        wordCloud.setColorPalette(new LinearGradientColorPalette(Color.RED, Color.BLUE, Color.GREEN, 30, 30));        wordCloud.setKumoFont(new KumoFont(font));//设置背景色        wordCloud.setBackgroundColor(new Color(255,255,255));//设置背景图片        //wordCloud.setBackground(new PixelBoundryBackground("E:\\爬虫/google.jpg"));//设置背景图层为圆形circle        //Dimension dimension = new Dimension(600, 600);        //设置为长方形        wordCloud.setBackground(new RectangleBackground(dimension));        //图层文字大小范围        wordCloud.setFontScalar(new  SqrtFontScalar(1, 40));//生成词云        wordCloud.build(wordFrequencyList);        wordCloud.writeToFile("E:\\wy.png");//Github：https://github.com/kennycason/kumo        //码云：https://gitee.com/lyy289065406/kumo        //长宽        Dimension dimension = new Dimension(800,600);//此处的设置采用内置常量即可，生成词云对象        WordCloud wordCloud = new WordCloud(dimension,CollisionMode.PIXEL_PERFECT);        //设置边界及字体        wordCloud.setPadding(2);        java.awt.Font font = new java.awt.Font("STSong-Light", 2, 20);//设置词云显示的三种颜色，越靠前设置表示词频越高的词语的颜色        wordCloud.setColorPalette(new LinearGradientColorPalette(Color.RED, Color.BLUE, Color.GREEN, 30, 30));        wordCloud.setKumoFont(new KumoFont(font));//设置背景色        wordCloud.setBackgroundColor(new Color(255,255,255));//设置背景图片        //wordCloud.setBackground(new PixelBoundryBackground("E:\\爬虫/google.jpg"));//设置背景图层为圆形circle        //Dimension dimension = new Dimension(600, 600);        //设置为长方形        wordCloud.setBackground(new RectangleBackground(dimension));        //图层文字大小范围        wordCloud.setFontScalar(new  SqrtFontScalar(1, 40));//生成词云        wordCloud.build(wordFrequencyList);        wordCloud.writeToFile("E:\\wy.png");

}
