package com.liang.argorithm.aboutproject.mapper;

import com.liang.argorithm.aboutproject.entity.MonitorWordDict;
import com.liang.argorithm.aboutproject.entity.MonitorWordDictExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface MonitorWordDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    long countByExample(MonitorWordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    int deleteByExample(MonitorWordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    int insert(MonitorWordDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    int insertSelective(MonitorWordDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    List<MonitorWordDict> selectByExampleWithBLOBs(MonitorWordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    List<MonitorWordDict> selectByExample(MonitorWordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    MonitorWordDict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    int updateByExampleSelective(@Param("record") MonitorWordDict record, @Param("example") MonitorWordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    int updateByExampleWithBLOBs(@Param("record") MonitorWordDict record, @Param("example") MonitorWordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    int updateByExample(@Param("record") MonitorWordDict record, @Param("example") MonitorWordDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    int updateByPrimaryKeySelective(MonitorWordDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    int updateByPrimaryKeyWithBLOBs(MonitorWordDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table monitor_word_dict
     * @mbg.generated 2022-11-02 15:38:34
     */
    int updateByPrimaryKey(MonitorWordDict record);

    int batchInsert(List<MonitorWordDict> dicts);
}